Repository azifydev/aziface-mobile, pull requests merged in 2025-08, with the labels that each got.

#3 fix: minimal adjusts in processors
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  android/build.gradle
  android/gradle.properties
  android/src/main/AndroidManifestNew.xml
  android/src/main/java/com/azify/azifacemobilesdk/AzifaceMobileSdkModule.java
  android/src/main/java/com/azify/processors/AuthenticateProcessor.java
  android/src/main/java/com/azify/processors/Config.java
  android/src/main/java/com/azify/processors/EnrollmentProcessor.java
  android/src/main/java/com/azify/processors/PhotoIDMatchProcessor.java
  example/.env.example
  example/.gitignore
  example/android/app/build.gradle
  example/android/build.gradle
  example/integrate-lock.json
  example/ios/.xcode.env.local
  example/ios/AzifaceMobileSdkExample.xcodeproj/project.pbxproj
  example/ios/AzifaceMobileSdkExample.xcodeproj/xcshareddata/xcschemes/AzifaceMobileSdkExample.xcscheme
  example/ios/AzifaceMobileSdkExample/Info.plist
  example/ios/AzifaceMobileSdkExample/PrivacyInfo.xcprivacy
  example/ios/Config.xcconfig
  example/ios/Podfile.lock
  example/package-lock.json
  example/package.json
  example/src/App.tsx
  example/src/Aziface.tsx
  example/src/Login.tsx
  example/src/helpers/store.ts
  example/src/hooks/useuser.hook.ts
  example/src/react-native-config.d.ts
  example/src/services/assemble.service.ts
  example/src/services/assembleApi.ts
  example/src/services/aziface.service.ts
  example/src/services/azifaceApi.ts
  example/src/services/azify.service.ts
  example/src/services/azifyApi.ts
  example/src/services/headers.ts
  ios/AzifaceMobileSdk.swift
  ios/Processors/PhotoIDMatchProcessor.swift
  ios/ViewController/AziFaceViewController.swift
  lefthook.yml
  package-lock.json
  package.json
  src/types/index.ts
Labels: bug, documentation, enhancement

#4 feat: add custom path route via params method
  README.md
  android/src/main/java/com/azify/azifacemobilesdk/AzifaceMobileSdkModule.java
  android/src/main/java/com/azify/processors/AuthenticateProcessor.java
  android/src/main/java/com/azify/processors/Config.java
  android/src/main/java/com/azify/processors/EnrollmentProcessor.java
  android/src/main/java/com/azify/processors/PhotoIDMatchProcessor.java
  android/src/main/java/com/azify/processors/PhotoIDScanProcessor.java
  android/src/main/java/com/azify/utils/CommonParams.java
  android/src/main/java/com/azify/utils/DynamicRoute.java
  example/ios/AzifaceMobileSdkExample.xcodeproj/project.pbxproj
  example/ios/Podfile.lock
  example/src/Aziface.tsx
  example/src/Login.tsx
  example/src/services/assemble.service.ts
  ios/AzifaceMobileSdk.swift
  ios/Config.swift
  ios/Processors/AuthenticateProcessor.swift
  ios/Processors/EnrollmentProcessor.swift
  ios/Processors/Helpers/ThemeHelpers.swift
  ios/Processors/Helpers/ThemeUtils.swift
  ios/Processors/LivenessCheckProcessor.swift
  ios/Processors/PhotoIDMatchProcessor.swift
  ios/Processors/PhotoIDScanProcessor.swift
  ios/Processors/ProcesingDelegate.swift
  ios/Utilities/CommonParams.swift
  ios/Utilities/DynamicRoute.swift
  ios/Utilities/FaceTecUtilities.swift
  ios/ViewController/AziFaceViewController.swift
  src/index.tsx
  src/types/index.ts
Labels: documentation, enhancement

#6 chore: new example client integration
  .github/CODEOWNERS
  example/.eslintrc.json
  example/ios/Podfile.lock
  example/package-lock.json
  example/package.json
  example/src/App.tsx
  example/src/Index.tsx
  example/src/Login.tsx
  example/src/Style.ts
  example/src/hooks/useuser.hook.ts
  example/src/routes/app.route.tsx
  example/src/routes/auth.route.tsx
  example/src/routes/index.tsx
  example/src/screens/Home.tsx
  example/src/screens/Login.tsx
  example/src/screens/Register.tsx
  example/src/screens/Style.ts
  example/src/screens/Welcome.tsx
  example/src/services/assemble.service.ts
  example/src/services/client.service.ts
  example/src/services/clientApi.ts
  example/src/types/react-native-config.d.ts
  example/src/types/types.ts
Labels: documentation

#8 fix(WL-65): resolve failed to read `.png` signature in release mode
  android/build.gradle
Labels: bug
